## 2709. Greatest Common Divisor Traversal

### My first approach with graph translation

In [52]:
import math


def prime_factors(n):
    factors = []
    for x in range(2, int(math.sqrt(n)) + 1):
        while n % x == 0:
            n //= x
            factors.append(x)
    if n > 1: factors.append(n)
    return factors


[prime_factors (n) for n in [1,2,4,5,6,7,18, 21, 33, 42]]

[[], [2], [2, 2], [5], [2, 3], [7], [2, 3, 3], [3, 7], [3, 11], [2, 3, 7]]

In [143]:
nums = [99991] * 100_000
nums = [42,40,45,42,50,33,30,45,33,45,30,36,44,1,21,10,40,42,42]

In [147]:
nums_primed = [prime_factors (n) for n in nums]
prime2idx = collections.defaultdict(list)

for i, primes in enumerate(nums_primed):
    for p in primes:
        prime2idx[p].append(i)
        
prime2idx = collections.defaultdict(set)

for i, primes in enumerate(nums_primed):
    print(f'{len(primes)=}')
    for p in primes:
        prime2idx[p].add(i)


prime2primes = collections.defaultdict(set)
for p, idx in prime2idx.items():
    
    primes = {p for i in idx for p in nums_primed[i]}
    prime2primes[p] = primes


all_primes = {p for ps in nums_primed for p in ps}

i = 0
stack = [p for p in nums_primed[i]]
visited_primes = set(stack)

while stack:
    p = stack.pop()
    
    children = prime2primes[p] - visited_primes
    for child_prime in children:
        visited_primes.add(child_prime)
        stack.append(child_prime)


len(visited_primes) == len(all_primes)



len(primes)=3
len(primes)=4
len(primes)=3
len(primes)=3
len(primes)=3
len(primes)=2
len(primes)=3
len(primes)=3
len(primes)=2
len(primes)=3
len(primes)=3
len(primes)=4
len(primes)=3
len(primes)=0
len(primes)=2
len(primes)=2
len(primes)=4
len(primes)=3
len(primes)=3


True

In [146]:
prime2primes

defaultdict(set,
            {2: {2, 3, 5, 7, 11},
             3: {2, 3, 5, 7, 11},
             7: {2, 3, 7},
             5: {2, 3, 5},
             11: {2, 3, 11}})

{2, 3, 5, 7, 11}

In [142]:
i = 0
stack = nums_primed[i]
visited_primes = set(stack)


True

set()

In [89]:
len(nums)

10000

In [90]:
import collections

In [91]:


nums_primed = [prime_factors (n) for n in nums]
prime2idx = collections.defaultdict(list)

for i, primes in enumerate(nums_primed):
    for p in primes:
        prime2idx[p].append(i)


i = 0

stack = [i]
visited = {i}

while stack:
    i = stack.pop()
    
    primes = nums_primed[i]
    for p in primes:
        routes = prime2idx[p]
        for j in routes:
            if j not in visited:
                visited.add(j)
                stack.append(j)

visited

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


### @Dummy nodes@ from editorial

Main idea: 

 - $g_i$ - node of the number
 - $d_p$ - dummy node for a particular prime





## 2092. Find All People With Secret

In [1]:
# Given: list of edges
# return: disjoint sets

In [33]:
meetings = [[0,2,1],[1,3,1],[4,5,1]]
# meetings = [[1,2], [1,3]]
n = 4


def get_disjoint_sets(sub_meetings):
    parent = [-1 for i in range(n)]

    def get_parent(x):
        if parent[x] == -1:
            parent[x] = x

        if parent[x] == x: return x
        
        return get_parent(parent[x])

    for edge in sub_meetings:
        x,y = edge[0], edge[1]
        
        x_parent = get_parent(x)
        y_parent = get_parent(y)
        # print(f'parent of {x=} is {x_parent=}')
        # print(f'parent of {y=} is {y_parent=}')
        parent[y_parent] = x_parent
        # print(f'{parent=}')

    meetings_rooms = {}
    for i,p in enumerate(parent):
        if p == -1: continue
        root_parent = get_parent(p)
        p = root_parent
        if p not in meetings_rooms:
            meetings_rooms[p] = [i]
        else:
            meetings_rooms[p].append(i)
        
    return meetings_rooms.values()


# graph_t = {}
# [1,2], [2,4], [5,6] 
# i = 0, x,y = 1,2
# graph_t = {1: [2], 2: [1]}

# i = 1, x,y = 2,4
# graph_t = {1: [2], 2: [1, 4], 4: [2]}

# i = 2, x,y = 5,6
# graph_t = {1: [2], 2: [1, 4], 4: [2], 5: [6], 6: [5]}
# [ [1,2,4], [5,6] ]

import collections

def get_disjoint_sets(sub_meetings):
    graph = collections.defaultdict(list)

    for edge in sub_meetings:
        x,y = edge[0], edge[1]

        graph[x].append(y)
        graph[y].append(x)
        

    # [ [1,2,4], [5,6] ]

    disjoint_sets = []
    visited = set()

    def explore_island(i):

        island = []
        stack = [i]
        visited.add(i)

        while stack:
            x = stack.pop()
            island.append(x)
            
            for child in graph[x]:
                if child not in visited:
                    stack.append(child)
                    visited.add(child)
        return island

    for node in graph.keys():
        if node not in visited:
            island = explore_island(node)
            disjoint_sets.append(island)

    return disjoint_sets

def test_disjoint_sets(edges, expected):
    actual = get_disjoint_sets(edges)

    print(f'{actual=} {expected=}')


test_disjoint_sets([[1,2], [1,3]], [[1,2,3]])
test_disjoint_sets([[1,2], [0,3], [4,5]], [[0,3], [1,2], [4,5]])
test_disjoint_sets([(3, 1), (0, 3)], [[0,1,3]])


actual=[[1, 3, 2]] expected=[[1, 2, 3]]
actual=[[1, 2], [0, 3], [4, 5]] expected=[[0, 3], [1, 2], [4, 5]]
actual=[[3, 0, 1]] expected=[[0, 1, 3]]


In [31]:
import collections

sub_meetings = [[1,2], [2,4], [5,6]]
sub_meetings = [(3, 1), (0, 3)]

# sub_meetings = [[1,2], [2,4], [5,6]]
# {1: [2], 2: [1, 4], 4: [2], 5: [6], 6: [5]}


def get_disjoint_sets(sub_meetings):
    graph = collections.defaultdict(list)

    for edge in sub_meetings:
        x,y = edge[0], edge[1]

        graph[x].append(y)
        graph[y].append(x)
        

    # [ [1,2,4], [5,6] ]

    disjoint_sets = []
    visited = set()

    def explore_island(i):

        island = []
        stack = [i]
        visited.add(i)

        while stack:
            x = stack.pop()
            island.append(x)
            
            for child in graph[x]:
                if child not in visited:
                    stack.append(child)
                    visited.add(child)
        return island

    for node in graph.keys():
        if node not in visited:
            island = explore_island(node)
            disjoint_sets.append(island)

    return disjoint_sets

get_disjoint_sets()

[[3, 0, 1]]

In [ ]:
meetings = [[3,1,3],[1,2,2],[0,3,3]]

In [44]:
"22".isdigit()

True

In [41]:
from collections import defaultdict

meetings = [[3,1,3],[1,2,2],[0,3,3], [3,4,2]]

In [42]:
graph = defaultdict(lambda: defaultdict(list))
for x, y, t in meetings:
    graph[t][x].append(y)
    graph[t][y].append(x)

# graph = {
#     2: {1: [2], 2: [1], 3: [4], 4: [3]},
#     3: {0: [3], 1: [3], 3: [0, 1]}
# }

# {0: [2], 2: [0], 1: [3], 3: [1], 4: [5], 5: [4]})
# # print(graph)


def f(t, node, visited):
    visited.add(node)

    if node in graph[t]:
        for c in graph[t][node]:
            if c not in visited:
                f(t, c, visited)
        
    return visited

knows = set([0, firstPerson])
for t, nodes in sorted(graph.items()):
    # t = 2
    # node = {1: [2], 2: [1], 3: [4], 4: [3]}

    for node in nodes.keys():
        if node not in knows:
            visited = f(t, node, set())

            if knows.intersection(visited) :
                knows |= visited
        
return knows

defaultdict(<function <lambda> at 0x10797dda0>, {3: defaultdict(<class 'list'>, {3: [1, 0], 1: [3], 0: [3]}), 2: defaultdict(<class 'list'>, {1: [2], 2: [1], 3: [4], 4: [3]})})


NameError: name 'firstPerson' is not defined

## ---



In [3]:
import numpy as np

np.cumsum([1, 4, 4, 4, 5, 8, 1, 1, 1, 2])

array([ 1,  5,  9, 13, 18, 26, 27, 28, 29, 31])

In [134]:
from collections import Counter

In [142]:
max(Counter([1,2,3,1]).items(), key=lambda t:t[1])[0]

1

In [136]:
max(Counter([1,2,3]))

3

## 1463. Cherry Pickup II

### Only single robot matters! (non-trivial test generator)

In [2]:
import numpy as np

In [40]:
m, n = 16,16

In [41]:
grid = np.random.randint(1, 15, size=(m,n))

i, j = np.meshgrid(np.arange(m), np.arange(n), indexing='ij')
grid[i >= j] = 0

grid

array([[ 0, 13,  5, 14,  3, 10,  2,  3,  4,  9, 10,  9, 10, 14,  3, 12],
       [ 0,  0, 14, 11,  6, 14,  7,  1,  4,  7,  6,  7,  9, 13,  3,  2],
       [ 0,  0,  0,  6,  5,  2, 12,  3,  8,  9,  9, 13,  9, 11,  6, 11],
       [ 0,  0,  0,  0,  9, 13,  4,  9, 13,  1, 13,  8,  7, 10,  9,  6],
       [ 0,  0,  0,  0,  0,  1,  8, 12,  8,  7,  7,  2, 14,  3,  7,  2],
       [ 0,  0,  0,  0,  0,  0, 13, 10, 10, 12,  2,  7,  6,  8, 11, 10],
       [ 0,  0,  0,  0,  0,  0,  0, 12, 12,  7,  3,  5,  2, 11,  7,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  2, 14,  8, 12, 12, 10,  9],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  5,  3, 13,  1,  5, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4, 13,  4, 11,  2, 14],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  9,  6,  1,  8],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2, 11,  2, 13],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  5, 14],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [44]:
print(str(grid.tolist()))

[[0, 13, 5, 14, 3, 10, 2, 3, 4, 9, 10, 9, 10, 14, 3, 12], [0, 0, 14, 11, 6, 14, 7, 1, 4, 7, 6, 7, 9, 13, 3, 2], [0, 0, 0, 6, 5, 2, 12, 3, 8, 9, 9, 13, 9, 11, 6, 11], [0, 0, 0, 0, 9, 13, 4, 9, 13, 1, 13, 8, 7, 10, 9, 6], [0, 0, 0, 0, 0, 1, 8, 12, 8, 7, 7, 2, 14, 3, 7, 2], [0, 0, 0, 0, 0, 0, 13, 10, 10, 12, 2, 7, 6, 8, 11, 10], [0, 0, 0, 0, 0, 0, 0, 12, 12, 7, 3, 5, 2, 11, 7, 5], [0, 0, 0, 0, 0, 0, 0, 0, 8, 2, 14, 8, 12, 12, 10, 9], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 5, 3, 13, 1, 5, 11], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 13, 4, 11, 2, 14], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 9, 6, 1, 8], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 11, 2, 13], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 5, 14], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [122]:
i, j = np.meshgrid(np.arange(m), np.arange(n), indexing='ij')

def is_invalid_j2(j2):
    return (m-i-2) > j

def is_invalid_j1(j2):
    return i < j

def is_valid_j2(i, j): return (m-i-2) <= j
def is_valid_j1(i, j): return j <= i

print(f'is_valid_j2=\n{is_valid_j2(i, j)}')

print(f'is_valid_j1=\n{is_valid_j1(i, j)}')

is_valid_j2=
[[False False  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]]
is_valid_j1=
[[ True False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]]


In [95]:
is_invalid_j1(j)

array([[False,  True,  True],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [48]:
grid = [
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,100,0,0],
    [2,0,0,0,1],
]

print(str(grid))

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 100, 0, 0], [2, 0, 0, 0, 1]]


In [47]:
m = len(grid)
n = len(grid[0])
dp = np.zeros((m,n), dtype=int)


def query_dp(i,j):
    if i < 0 or i >= m or j < 0 or j >= n or not ((m-i-1) <= j): return 0
    return dp[i][j]


def max_from(i,j):
    return max(query_dp(i-1, j-1), query_dp(i-1, j+1), query_dp(i-1, j))

for i in range(m):
    for j in range(n):
        dp[i][j] = grid[i][j] + max_from(i,j)
        
dp

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0, 100,   0,   0],
       [  2, 100, 100, 100,   1]])

In [39]:
grid

array([[ 0, 10,  1,  7],
       [ 0,  0,  8,  5],
       [ 0,  0,  0,  3],
       [ 0,  0,  0,  0]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [6]:
grid = np.zeros((m,n), dtype=np.int16)




grid

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

### Brute force recursion

In [73]:
grid = [
    [3,1,1],
    [2,5,1],
    [1,5,5],
    [2,1,1]
]

m = len(grid)
n = len(grid)

grid

[[3, 1, 1], [2, 5, 1], [1, 5, 5], [2, 1, 1]]

In [66]:
from functools import cache

In [68]:
m = 10
n = 10


@cache
def possible_trajectories(i,j):
    if i == m - 1:
        return [[(i,j)]]
    
    trs = []
    trs += [[(i,j)] + t for t in possible_trajectories(i+1, j)]
    if j > 0:
        trs += [[(i,j)] + t for t in possible_trajectories(i+1, j-1)]
    if j < n - 1:
        trs += [[(i,j)] + t for t in possible_trajectories(i+1, j+1)]
    return trs

trs1 = possible_trajectories(0,0)
# trs2 = possible_trajectories(0, n-1)

len(trs1)

6046

In [ ]:
dp = np.zeros((m,n,), dtype=np.int32)
dp[0,0] = grid[0][0]
dp[0,n-1] = grid[0][n-1]

In [128]:
def prev_move_opts(jn):
    return [j for j in (jn+1, jn, jn-1) if j >= 0 and j < n]

prev_move_opts(0), prev_move_opts(1), prev_move_opts(2)

([1, 0], [2, 1, 0], [2, 1])

In [133]:
grid = [
    [3,1,1],
    [2,5,1],
    [1,5,5],
    [2,1,1]
]

grid = [[9,3,1,2],[9,9,2,2],[8,4,8,3],[9,2,7,7]]

m = len(grid)
n = len(grid[0])


def cartesian_product(A, B):
    for a in A: 
        for b in B: yield (a,b)

def is_valid_j1(i, j): return j <= i
def is_valid_j2(i, j): return (m-i-2) <= j

def collect1(i,j):
    return grid[i][j] if is_valid_j1(i,j) else 0


def collect2(i,j):
    return grid[i][j] if is_valid_j2(i,j) else 0


def brute(i, j1, j2):
    harvest = [collect1(i,j1), collect2(i, j2)]
    harvest = sum(harvest) if j1 != j2 else max(harvest)
    if i == 0:
        return harvest
    res = 0
    for prev_j1 in prev_move_opts(j1):
        for prev_j2 in prev_move_opts(j2):
            res = max(res, brute(i-1, prev_j1, prev_j2))
    
    return res + harvest


all_j_opts = cartesian_product(range(n), range(n))
max([brute(m-1, j1, j2) for j1,j2 in all_j_opts])


60

In [102]:
m = len(grid)
n = len(grid[0])

def cartesian_product(A, B):
    for a in A: 
        for b in B: yield (a,b)
        

def prev_move_opts(jn):
    return [j for j in (jn+1, jn, jn-1) if j >= 0 and j < n]

def is_invalid_j2(i, j):
    return (m-i-2) > j

def is_invalid_j1(i, j):
    return i < j

def collect_

@cache
def brute(i, j1, j2):
    if i == 0:
        c = 0
        if j1 == 0: c += grid[0][j1]
        if j2 == n-1: c += grid[0][j2]
        return c

(j1,j2)=(0, 0) 3
(j1,j2)=(0, 1) 3
(j1,j2)=(0, 2) 4
(j1,j2)=(1, 0) 0
(j1,j2)=(1, 1) 0
(j1,j2)=(1, 2) 1
(j1,j2)=(2, 0) 0
(j1,j2)=(2, 1) 0
(j1,j2)=(2, 2) 1


0

In [105]:
is_invalid_j2(1, 0)

True

In [88]:
def cartesian_product(A, B):
    for a in A: 
        for b in B: yield (a,b)
        
        
def prev_move_opts(jn):
    return [j for j in (jn+1, jn, jn-1) if j >= 0 and j < n]
        

def brute(i, j1, j2):
    if i == 0:
        c = 0
        if j1 == 0: c += grid[0][j1]
        if j2 == n-1: c += grid[0][j2]
        return c

    j1_opts = prev_move_opts(j1)
    j2_opts = prev_move_opts(j2)
    prev = max(brute(i-1, prev_j1, prev_j2) for prev_j1, prev_j2 in cartesian_product(j1_opts, j2_opts))
    
    res = prev grid[i][j1]
    if j1 != j2:
        res += grid[i][j2]
    return res

all_j_opts = cartesian_product(range(n), range(n))
max([brute(m-1, j1, j2) for j1,j2 in all_j_opts])

24

3

## 368. Largest Divisible Subset

### Brute Force! $O(2^n \times n^2)$

In [8]:
nums = [1,2,4,8]

In [9]:
can_join([], 2)

True

In [11]:
def is_good_pair(x,y): return not(x%y and y%x)

def can_join(arr, x): return all(is_good_pair(x,y) for y in arr)


subsets = [[]]
best_subset = []

for n in nums:
    with_n = []
    for s in subsets:
        if can_join(s, n):
            sn = [n]+s
            with_n.append(sn)
            if len(sn) > len(best_subset):
                best_subset = sn
    subsets += with_n

subsets, best_subset

([[],
  [1],
  [2],
  [2, 1],
  [4],
  [4, 1],
  [4, 2],
  [4, 2, 1],
  [8],
  [8, 1],
  [8, 2],
  [8, 2, 1],
  [8, 4],
  [8, 4, 1],
  [8, 4, 2],
  [8, 4, 2, 1]],
 [8, 4, 2, 1])

In [1]:
import array

In [7]:
array.array
            )

array('B', [0])

## 1043. Partition Array for Maximum Sum

### [✅] Generate all partitions into sub-arrays for fun and profit!

In [34]:
arr = [1,15,7,9,2,5,10]

arr = [1,2,3]
"""
expected:
[
 [ [1], [2], [3] ],
 [ [1], [2, 3]   ],
 [ [1, 2], [3]   ]
 [ [1, 2, 3]     ],
]
"""



def partition(i):
    if i >= len(arr): return [[]]

    result = []
    upper_bounds = list( range(i+1, min(i+k, len(arr))+1) )
    # print(f'{upper_bounds=} for {i=} {arr[i]=} ')
    for upper_boundary in upper_bounds:
        for p in partition(upper_boundary):
            r = [arr[i:upper_boundary]] + p
            result.append(r)
    return result


arr = [1,15,7,  9,2,5,  10]
k = len(arr)
k = 3

for p in partition(0):
    print(p)

print(len(partition(0)))

[[1], [15], [7], [9], [2], [5], [10]]
[[1], [15], [7], [9], [2], [5, 10]]
[[1], [15], [7], [9], [2, 5], [10]]
[[1], [15], [7], [9], [2, 5, 10]]
[[1], [15], [7], [9, 2], [5], [10]]
[[1], [15], [7], [9, 2], [5, 10]]
[[1], [15], [7], [9, 2, 5], [10]]
[[1], [15], [7, 9], [2], [5], [10]]
[[1], [15], [7, 9], [2], [5, 10]]
[[1], [15], [7, 9], [2, 5], [10]]
[[1], [15], [7, 9], [2, 5, 10]]
[[1], [15], [7, 9, 2], [5], [10]]
[[1], [15], [7, 9, 2], [5, 10]]
[[1], [15, 7], [9], [2], [5], [10]]
[[1], [15, 7], [9], [2], [5, 10]]
[[1], [15, 7], [9], [2, 5], [10]]
[[1], [15, 7], [9], [2, 5, 10]]
[[1], [15, 7], [9, 2], [5], [10]]
[[1], [15, 7], [9, 2], [5, 10]]
[[1], [15, 7], [9, 2, 5], [10]]
[[1], [15, 7, 9], [2], [5], [10]]
[[1], [15, 7, 9], [2], [5, 10]]
[[1], [15, 7, 9], [2, 5], [10]]
[[1], [15, 7, 9], [2, 5, 10]]
[[1, 15], [7], [9], [2], [5], [10]]
[[1, 15], [7], [9], [2], [5, 10]]
[[1, 15], [7], [9], [2, 5], [10]]
[[1, 15], [7], [9], [2, 5, 10]]
[[1, 15], [7], [9, 2], [5], [10]]
[[1, 15], [7], [9,

### Solve somehow

In [46]:
arr = [1,15,7,9,2,5,10]
k = 3

arr = [1,4,1,5,7,3,6,1,9,9,3]
k = 4
# arr = [5,10]
dp = [0 for _ in range(len(arr))]
def s(i): return 0 if i >= len(arr) else dp[i]

for i in range(len(arr)-1, -1, -1):
    m = arr[i]
    for t in range(min(k, len(arr)-i)): # TODO!
        m = max(m, arr[i+t])
        dp[i] = max(dp[i], (t+1)*m + s(i+t+1))
dp

[83, 82, 75, 68, 61, 54, 45, 36, 27, 18, 3]

## 1291. Sequential Digits

#### Mini quest 0: create iterator through this space

In [7]:
digits = list(range(1, 10))
digits

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
def d2n(digits): return sum([d * 10**i for i,d in enumerate(reversed(digits))])

In [24]:
nums = []

for n in range(1, 10):
    
    for i in range(9-n+1):
        num = (d2n(digits[i:i+n]))
        nums.append(num)


print(len(nums))
print(nums)

45
[1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 23, 34, 45, 56, 67, 78, 89, 123, 234, 345, 456, 567, 678, 789, 1234, 2345, 3456, 4567, 5678, 6789, 12345, 23456, 34567, 45678, 56789, 123456, 234567, 345678, 456789, 1234567, 2345678, 3456789, 12345678, 23456789, 123456789]
